### ISSUE TITLE
Reply

### ISSUE THREAD

**Issue by HeskeyBaozi** [NingMew/NingMew.github.io#1]
1. 
```
`aaa`, `bbb`
```

2.
```yml
tags:
  - aaa
  - bbb
```

3. 顶部菜单只能导航到站内页面。导航到外链。请使用社交链接：
```yml
social:
  other_blog: https://blog.chenqiqian.com/

social_icons:
  enable: true
  other_blog: fa-link
```
